//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeAppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreateAccount()
        {
            this.Deposites = new HashSet<Deposite>();
            this.Interests = new HashSet<Interest>();
            this.Widtrows = new HashSet<Widtrow>();
        }
    
        public int id { get; set; }
        public string accountNo { get; set; }
        public string holderName { get; set; }
        public string nic { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> typeId { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposite> Deposites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interest> Interests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Widtrow> Widtrows { get; set; }
    }
}
