//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeAppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracticeDBEntities : DbContext
    {
        public PracticeDBEntities()
            : base("name=PracticeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<CreateAccount> CreateAccounts { get; set; }
        public virtual DbSet<Deposite> Deposites { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Widtrow> Widtrows { get; set; }
    }
}
